### ISSUE TITLE
 Plugin autopilot N/A is already installed. Uninstalling existing plugin...

### ISSUE THREAD

**Issue by Azgher** [contraband/autopilot#48]
Getting the below error when trying to cf install autopilot on a tfs agent.

Plugin autopilot N/A is already installed. Uninstalling existing plugin...
accept tcp 127.0.0.1:55925: use of closed network connection
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
main.AutopilotPlugin.parseArgs(0xc0820263e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/cb/workspace/go/src/github.com/concourse/autopilot/autopilot.go:65 +0x2c7
main.AutopilotPlugin.Run(0x193620, 0xc082004f30, 0xc0820263e0, 0x1, 0x1)
/Users/cb/workspace/go/src/github.com/concourse/autopilot/autopilot.go:27 +0xd2
main.(*AutopilotPlugin).Run(0x9730c8, 0x193620, 0xc082004f30, 0xc0820263e0, 0x1, 0x1)
:1 +0xd0
github.com/cloudfoundry/cli/plugin.Start(0x192500, 0x9730c8)
/Users/cb/workspace/go/src/github.com/cloudfoundry/cli/plugin/plugin_shim.go:18 +0x251
main.main()
/Users/cb/workspace/go/src/github.com/concourse/autopilot/autopilot.go:20 +0x66
exit status 2
[31;1mFAILED

The version on the CF-Community(https://plugins.cloudfoundry.org/) is two versions behind the latest release (0.0.1 vs. 0.0.3). Is that due to that?

**Comment by xoebus** [comment]
There was an error when uninstalling which was fixed in https://github.com/contraband/autopilot/pull/47 and then released in 0.0.4 which was pushed to the CLI plugin repository in December. Does using that version fix this problem?
